remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/


footer_content: 'Copyright &copy; Lee seulgi. 방문해주셔서 감사합니다. :D'


# Site Settings
title                    : "백설 집사의 블로그"
title_separator          : "-"
name                     : "백설집사"
descriptiobn             : "집사와 개발자를 맡고 있습니다."
url                      : "https://sss5793.github.io"

comment:
    provider: disqus
    shortname: "sss5793-github-io"


ga_tracking: "UA-154244632-1"
