theme: jekyll-theme-leap-day

# Site
name: '블로그 제목'
description: '블로그 설명'
meta_description: '블로그 메타테그'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/저장소이름/'
google_analytics: ''
disqus: '' #댓글 api 이용시 disqus-id 입력
mailchimp-list: ''

# Authors
authors:
  sal:
    name: 사용자 이름
    display_name: 표시될 이름
    gravatar: 
    email: email@gmail.com
    web: https://username.github.io
    twitter: https://twitter.com/username
    description: "사용자 설명"
