remote_theme: pmarsceill/just-the-docs
search_enabled: true


search_tokenizer_separator: /[\s/]+/


footer_content: "Copyright &copy; Lee seulgi. Distributed by an <a href=\"https://sss5793.github.io/"></a>"


# Site Settings
title                    : "백설 집사의 개발 블로그"
title_separator          : "-"
name                     : "백설집사"
descriptiobn             : "집사와 개발자를 맡고 있습니다."
url                      : "https://sss5793.github.io"
